CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
    USER_NAME TEXT UNIQUE NOT NULL,
    USER_ROLE TEXT NOT NULL,
    AGE INTEGER NOT NULL,
    USER_STATE TEXT NOT NULL
);

CREATE TABLE CATEGORIES (
	ID SERIAL PRIMARY KEY,
    CATEGORY_NAME TEXT UNIQUE,
    DESCRIPTION TEXT,
    PRODUCT_COUNT INTEGER
);

CREATE TABLE PRODUCTS(
	ID SERIAL PRIMARY KEY,
    PRODUCT_NAME TEXT NOT NULL,
    SKU TEXT UNIQUE NOT NULL,
    CATEGORY_ID INTEGER REFERENCES CATEGORIES(ID) NOT NULL,
    PRICE DECIMAL NOT NULL,
    OWNER_ID INTEGER REFERENCES USERS(ID) NOT NULL
);

CREATE TABLE PRODUCT_ORDER(
	ID SERIAL PRIMARY KEY,
    QUANTITY INTEGER,
    USER_ID INTEGER REFERENCES USERS(ID) NOT NULL,
    PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID) NOT NULL,
    ORDER_NUMBER INTEGER,
    PRICE DECIMAL,
    PURCHASE_DATE TIMESTAMP
);
